config/routes.rb
Qtest::Application.routes.draw do
	match '/' => 'Question#show_all', as: 'root'
	match '/add' => 'Question#add', method: 'post', as: 'add_question'
	match '/:id/add' => 'Comment#add', method: 'post', as: 'add_comment'
	match '/:id/answer' => 'Question#answer', method: 'post', as: 'answer_question'
	match '/:id' => 'Question#show', as: 'show_question'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :question
	validates_presence_of :question
	validates_presence_of :content
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :comment
	validates_presence_of :question_content
	validates_each :has_answer do |record, attr, value|
      record.errors.add(attr, 'doesn\'t have an answer body but has_answer is true') if (record.has_answer ==  true) and (record.answer_content.blank? == true)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
	def add
		q = Question.find(params[:id])
		raise "can't comment unanswered question" if not q.has_answer
		Comment.new(question_id: q.id, content: params[:content]).save
		redirect_to show_question_path(q)
	end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	def index
	
	end
end

app/controllers/question_controller.rb
class QuestionController < ApplicationController
	def show_all
		@questions = Question.all
	end
	
	def show
		@question = Question.find(params[:id])
	end
	
	def add
		q = Question.new(question_content: params[:content])
		q.save
		redirect_to({action: 'show', id: q.id})
	end
	
	def answer
		q = Question.find(params[:id])
		raise "already has answer" if q.has_answer		
		q.answer_content = params[:content]
		q.has_answer = true
		q.save
		redirect_to({action: 'show', id: q.id})
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qtest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/question/show.html.haml
%a{href: root_path}
	Return to questions list
- q = @question
%h3= "Question ##{q.id}"
%p 
	%b Q: 
	= q.question_content
- if q.has_answer then
	%p
		%b A:
		= q.answer_content
	- form_title = 'Leave a comment:'
	- form_action_path = add_comment_path
- else
	- form_title = 'Answer the question:'
	- form_action_path = answer_question_path
	
%div{style: 'margin-left: 50px; margin-top: 50px'}	
	- q.comment.each_with_index do |c, i|
		%h4= "Comment ##{i+1}"
		%p
			=c.content
		%hr

	%form{method: 'post', action: form_action_path}
		%h2= form_title
		%p
			%textarea{name: 'content', cols: 40, rows: 5}
		%input{type: 'submit'}

app/views/question/show_all.html.haml
- @questions.each do |q|
	%a{href: show_question_path(q)}
		%h3= "Question ##{q.id}"
	%p 
		%b Q: 
		= q.question_content
	- if q.has_answer then
		%p
			%b A:
			= q.answer_content
		- url_text = 'Leave a comment'
	- else
		- url_text = 'Answer the question'
	%a{href: show_question_path(q)}= url_text
	- if q.has_answer then
		%span= ' | ' + q.comment.count.to_s + ' comment(s)'
	%hr
	
%form{method: 'post', action: add_question_path}
	%h2 Ask a question:
	%p
		%textarea{name: 'content', cols: 40, rows: 5}
	%input{type: 'submit'}